// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diqdsmrlhldanxxrtozl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpcWRzbXJsaGxkYW54eHJ0b3psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzg2NzYsImV4cCI6MjA2NDYxNDY3Nn0.5btkbuhvf0CLye5pQh7bp8cmihJcMTChMlclBKRaNmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);